### ISSUE TITLE
期中報告

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/vecp2018#12]
第九週前以 3 人一組, 完成下列要求:

整理 #11 中所列出的 Lua 程式語法
利用 http://mde.tw/vecp2018/lua/SchoolProject/ 繪製虎尾科技大學校徽
利用 http://mde.tw/vecp2018/lua/SchoolProject/ 繪製美國國旗
請將上述內容寫在各組的 vecp2018 倉儲中

各組員完成期中報告後, 請將連結留在下列 comments 中.

**Comment by 40628434** [comment]
- 導入“js”模組
local js = require“js” 
- 全局就是javascript的窗口
local global = js.global 
local document = global.document 
- html檔案中canvas id設為“canvas” 
local canvas = document ：getElementById（“canvas”）
- 將ctx設為canvas 2d繪圖畫布變數
local ctx = canvas：getContext（“2d”）

- 屬性呼叫使用。而方法呼叫使用：
- 設定填圖顏色
ctx.fillStyle =“rgb（200,0,0）” 
- 設定畫筆顏色
ctx.strokeStyle =“rgb（0,0,200）”

- 乘上deg可轉為徑度單位
deg = math.pi / 180

- 建立多邊形定點位置畫線
函數function star（radius，xc，yc，n）-- 
radius = 100 - 
xc = 200 
--yc = 200 
xi = xc + radius math.cos（（360 / n）度+ 360度）
YI = YC -半徑 math.sin（（360 / N）度+ 360度）
CTX：beginPath方法（）
CTX：的moveTo（XI，YI）
對於i = 2，N + 1做
X = XC +半徑math.cos（（360 / N）度 I + 360度）
Y = YC -半徑math.sin（（360 / N）度 I + 360度）
CTX：了lineTo（X，Y）
結束
端

- 以下利用多邊形畫線函式呼叫執行畫框線或填入顏色
- 畫五邊形框線
star（200，300，200，6）
ctx：closePath（）
ctx：stroke（）

- 以下利用多邊形畫線函式呼叫執行畫框線或填入顏色
- 畫五邊形框線
ctx.fillStyle ='＃191970'star 
（200，300，200，6）
ctx：closePath（）
ctx ：填（）

- 裡面白色六邊型
ctx.fillStyle ='#fff'star（120，300，200，6 
）
ctx：closePath（）
ctx：fill（）

- 中間圓
ctx.fillStyle ='＃191970'star 
（50，300，200，40 ）
ctx：closePath（）
ctx：fill（）

- 中間白色
ctx.fillStyle ='#fff'star（20,270,170,4 
）
ctx：closePath（）
ctx：fill（）

- 中間白色
ctx.fillStyle ='#fff'star（20,280,180,4 
）
ctx：closePath（）
ctx：fill（）

- 中間白色
ctx.fillStyle ='#fff'star（20,290,190，4 
）
ctx：closePath（）
ctx：fill（）

- 中間白色
ctx.fillStyle ='#fff'star（20，300，200，4 
）
ctx：closePath（）
ctx：fill（）

- 中間白色
ctx.fillStyle ='#fff'star（20,310,210,4 
）
ctx：closePath（）
ctx：fill（）

- 中間白色
ctx.fillStyle ='#fff'star（20,320,220,4 
）
ctx：closePath（）
ctx：fill（）

- 中間白色
ctx.fillStyle ='#fff'star（20,330,230,4 
）
ctx：closePath（）
ctx：fill（）

- 中間長方形

ctx.fillStyle ='#fff'star（90，200，20，6 
）
ctx：closePath（）
ctx：fill（）

ctx.fillStyle ='#fff'star（90,290,20,6 
）
ctx：closePath（）
ctx：fill（）

ctx.fillStyle ='#fff'star（90,380,20,6 
）
ctx：closePath（）
ctx：fill（）

ctx.fillStyle ='#fff'star（90,400,20,6 
）
ctx：closePath（）
ctx：fill（

**Comment by a40628404** [comment]
https://a40628404.github.io/vecp2018-04/midterm/index.html

**Comment by 40628427** [comment]
https://40628427.github.io/vecp2018-27/midterm/index.html

**Comment by 40628412** [comment]
https://40628412.github.io/vecp2018-12/midterm/index.html

**Comment by 40628437** [comment]
https://40628437.github.io/vecp2018-37/midterm/index.html

**Comment by 40628428** [comment]
https://40628428.github.io/vecp2018-28/midterm/index.html

**Comment by 40628408** [comment]
https://40628408.github.io/vecp2018-08/midterm/index.html

**Comment by 40628410** [comment]
https://40628410.github.io/vecp2018-10/midterm/index.html

**Comment by 40628413** [comment]
https://40628413.github.io/vecp2018-13/midterm/index.html

**Comment by 40628402** [comment]
https://40628402.github.io/vecp2018-02/midterm/index.html

**Comment by 40628407** [comment]
https://40628407.github.io/vecp2018-7/midterm/index.html

**Comment by bobXDC** [comment]
https://bobXDC.github.io/vecp2018-1/midterm/index.html

**Comment by bobXDC** [comment]
https://40628401.github.io/vecp2018-1/midterm/index.html

**Comment by bobXDC** [comment]
https://bobXDC.github.io/vecp2018-1/midterm/index.html

**Comment by bobXDC** [comment]
https://40628401.github.io/vecp2018-1/midterm/index.html

**Comment by bobXDC** [comment]
55

**Comment by bobXDC** [comment]
https://bobXDC.github.io/vecp2018-1/midterm/index.html

學號;40628401

**Comment by 40628423** [comment]
https://40628423.github.io/vecp2018-23/midterm/index.html

**Comment by 40628405** [comment]
https://40628405.github.io/vecp2018-05/midterm/index.html

**Comment by 40628405** [comment]
https://40628405.github.io/vecp2018-05/midterm/index.html

**Comment by 40628440** [comment]
https://40628440.github.io/vecp2018-40/midterm/index.html

**Comment by a40628450** [comment]
https://a40628450.github.io/vecp2018-50/midterm/index.html

**Comment by 40628424** [comment]
https://40628424.github.io/vecp2018/midterm/index.html

**Comment by 40628436** [comment]
https://40628436.github.io/vecp2018-36/midterm/index.html

**Comment by 40628435** [comment]
https://40628435.github.io/vecp2018/index.html

**Comment by 40628418** [comment]
https://40628418.github.io/vecp2018-18/midterm/index.html

**Comment by 40628417** [comment]
https://40628417.github.io/vecp2018/index.html

**Comment by 40628431** [comment]
https://40628431.github.io/vecp-2018/midterm/index.html

**Comment by 40628425** [comment]
https://40628425.github.io/vecp2018/midterm/index.html

**Comment by 40628414** [comment]
https://40628414.github.io/vecp2018_14/midterm/index.html

**Comment by 40628446** [comment]
https://40628446.github.io/vecp2018/index.html

**Comment by 40628439** [comment]
https://40628439.github.io/406284-39/midterm/index.html

**Comment by 40628416** [comment]
https://40628416.github.io/vecp2018-16/midterm/index.html

**Comment by 40328410** [comment]
https://40328410.github.io/vecp2018/midterm/index.html

**Comment by 40328421** [comment]
https://40328421.github.io/vecp2018-21/midterm/index.html

**Comment by 40628411** [comment]
https://40628411.github.io/vecp2018-11/midterm/index.html

**Comment by 40628434** [comment]
vecp2018-34 /README.md

**Comment by 40628434** [comment]
https://github.com/40628434/vecp2018-34/blob/master/README.md

**Comment by 40628434** [comment]
https://40628434.github.io/vecp2018-34/midterm/index.html

**Comment by 40628410** [comment]
https://40628410.github.io/vecp2018-10/midterm/index.html

**Comment by 40628453** [comment]
https://40628453.github.io/vecp2018-53/LICENSE.md/index.html

**Comment by 40628442** [comment]
https://40628442.github.io/vecp2018-42/midterm/index.html

**Comment by 40628451** [comment]
https://40628451.github.io/vecp2018_51/LICENS.md/index.html

**Comment by 40628432** [comment]
https://github.com/40628432/vecp2018-32/tree/gh-pages

**Comment by 40628448** [comment]
https://40628448.github.io/vecp2018-48/index.html

**Comment by 40628455** [comment]
https://40628455.github.io/VECP2018_55/index.html

**Comment by 40628433-1** [comment]
https://40628433-1.github.io/vecp2018-33/index.html
學號:40628433
