### ISSUE TITLE
分組期末網站回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/vecp2018#18]
請各組完成 Heroku 分組內容管理網站後, 將連結回報至下列 comment 中.

**Comment by 40628414** [comment]
https://vecp-40628435.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628408** [comment]
https://vecp-40628408.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628427** [comment]
https://vecp-40628427.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40328410** [comment]
http://vecp-40328410.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628453** [comment]
https://vecp-40628451.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by bobXDC** [comment]
https://vecp-40628407.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628407** [comment]
https://vecp-40628407.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628442** [comment]
http://vecp-40628442.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628440** [comment]
http://vecp-a40628440.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628418** [comment]
http://vecp-40628418.herokuapp.com

**Comment by 40628418** [comment]
http://vecp-40628418.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628431** [comment]
https://vecp-40628431.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628410** [comment]
https://vecp-40628405.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by a40628404** [comment]
https://vecp-40628404.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B

**Comment by 40628402** [comment]
https://vecp-40628402.herokuapp.com/get_page/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B
