### ISSUE TITLE
期末查驗

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/vecp2018#19]
# G19

https://vecp-40628435.herokuapp.com/lua40628435
https://vecp-40628435.herokuapp.com/lua40628414
https://vecp-40628435.herokuapp.com/lua40628417

# G1

https://vecp-40628408.herokuapp.com/lua40628408
https://vecp-40628408.herokuapp.com/lua40628428
https://vecp-40628408.herokuapp.com/lua40628436

# G11

https://vecp-40628427.herokuapp.com/lua40628427
https://vecp-40628427.herokuapp.com/lua40628437
https://vecp-40628427.herokuapp.com/lua40628412

# G13

https://vecp-40328410.herokuapp.com/lua40328410
https://vecp-40328410.herokuapp.com/lua40628448
https://vecp-40328410.herokuapp.com/lua40328421

# G9

https://vecp-40628451.herokuapp.com/lua40628451
https://vecp-40628451.herokuapp.com/lua40628453
https://vecp-40628451.herokuapp.com/lua40628438

# G17

https://vecp-40628407.herokuapp.com/lua40628407
https://vecp-40628407.herokuapp.com/lua40628401
https://vecp-40628407.herokuapp.com/lua40628445

# G18

https://vecp-40628442.herokuapp.com/lua40628442
https://vecp-40628442.herokuapp.com/lua40628452
https://vecp-40628442.herokuapp.com/lua40628454

# G15

https://vecp-a40628440.herokuapp.com/lua40628440
https://vecp-a40628440.herokuapp.com/lua40628413
https://vecp-a40628440.herokuapp.com/lua40628450

# G12

https://vecp-40628418.herokuapp.com/lua40628418
https://vecp-40628418.herokuapp.com/lua40628411
https://vecp-40628418.herokuapp.com/lua40628421

# G10

https://vecp-40628431.herokuapp.com/lua40628431
https://vecp-40628431.herokuapp.com/lua40628424
https://vecp-40628431.herokuapp.com/lua40628425

# G14

https://vecp-40628405.herokuapp.com/lua40628405
https://vecp-40628405.herokuapp.com/lua40628410
https://vecp-40628405.herokuapp.com/lua40628416

# G7

https://vecp-40628404.herokuapp.com/lua40628404
https://vecp-40628404.herokuapp.com/lua40628422
https://vecp-40628404.herokuapp.com/lua40628456

**Comment by 40628423** [comment]
# G6
https://vecp-40628423.herokuapp.com/lua40628423
https://vecp-40628423.herokuapp.com/lua40628446

**Comment by 40628402** [comment]
### G12
https://vecp-40628402.herokuapp.com/lua40628402
