### ISSUE TITLE
組員期末簡報上傳

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/vecp2018#21]
請各學員將 pptx 簡報檔案上傳至下列回應中.

以下為測試簡報上傳:

[test.pptx](https://github.com/mdecourse/vecp2018/files/2148973/test.pptx)

**Comment by a40628404** [comment]
[lua.pptx](https://github.com/mdecourse/vecp2018/files/2148988/lua.pptx)

https://github.com/a40628404/vecp2018-04/blob/gh-pages/lua.pptx

**Comment by 40628423** [comment]
[計算機程式期末報告.pptx](https://github.com/mdecourse/vecp2018/files/2148991/default.pptx)

**Comment by 40628435** [comment]
[計算機程式報告.pptx](https://github.com/mdecourse/vecp2018/files/2148993/default.pptx)

https://github.com/40628435/vecp2018/blob/gh-pages/default.pptx

**Comment by 40628446** [comment]
[計算機程式設計報告(46).pptx](https://github.com/mdecourse/vecp2018/files/2148998/46.pptx)

https://github.com/40628446/vecp2018/blob/gh-pages/46.pptx

**Comment by 40628448** [comment]
[計算機程式設計報告48.pptx](https://github.com/mdecourse/vecp2018/files/2149000/48.pptx)

https://github.com/40628448/vecp2018-48/blob/gh-pages/48.pptx

**Comment by 40628453** [comment]
[40628453 計算基程式.pptx](https://github.com/mdecourse/vecp2018/files/2149005/40628453.pptx)

**Comment by 40628424** [comment]
[Lua.pptx](https://github.com/mdecourse/vecp2018/files/2149027/Lua.pptx)

**Comment by 40628424** [comment]
[計算機程式報告Lua.pptx](https://github.com/mdecourse/vecp2018/files/2149049/Lua.pptx)

**Comment by 40628431** [comment]
[LUA報告.pptx](https://github.com/mdecourse/vecp2018/files/2149055/LUA.pptx)

**Comment by 40628425** [comment]
[計算機程式報告.pptx](https://github.com/mdecourse/vecp2018/files/2149081/default.pptx)

**Comment by 40328410** [comment]
[期末報告.pptx](https://github.com/mdecourse/vecp2018/files/2149068/default.pptx)

**Comment by 40628417** [comment]
[計算機程式設計報告(1).pptx](https://github.com/mdecourse/vecp2018/files/2149075/1.pptx)

https://github.com/40628417/vecp2018/blob/gh-pages/1.pptx

**Comment by 40628437** [comment]
[計算機程式期末報告.pptx](https://github.com/mdecourse/vecp2018/files/2149080/default.pptx)

**Comment by 40628445** [comment]
[40628445 計算機程式報告.pptx](https://github.com/mdecourse/vecp2018/files/2149082/40628445.pptx)

**Comment by 40628402** [comment]
[default.pdf](https://github.com/mdecourse/vecp2018/files/2149085/default.pdf)

**Comment by 40628405** [comment]
[計算機程式期末報告.pptx](https://github.com/mdecourse/vecp2018/files/2149086/default.pptx)

**Comment by 40628427** [comment]
[計算機程式報告(40628427).pptx](https://github.com/mdecourse/vecp2018/files/2149094/40628427.pptx)

**Comment by 40628439** [comment]
[簡報1.pptx](https://github.com/mdecourse/vecp2018/files/2149096/1.pptx)

**Comment by 40628403** [comment]
[40628403.pptx](https://github.com/mdecourse/vecp2018/files/2149110/40628403.pptx)

**Comment by 40628408** [comment]
[40628408計算機程式(lua).pptx](https://github.com/mdecourse/vecp2018/files/2149111/40628408.lua.pptx)

**Comment by 40628436** [comment]
[程式計算機.pptx](https://github.com/mdecourse/vecp2018/files/2149115/default.pptx)

**Comment by 40628442** [comment]
[40628442李承洋.pptx](https://github.com/mdecourse/vecp2018/files/2149118/40628442.pptx)

**Comment by 40628407** [comment]
[計算機程式.pptx](https://github.com/mdecourse/vecp2018/files/2149114/default.pptx)

**Comment by 40628414** [comment]
[計算機程式報告14.pptx](https://github.com/mdecourse/vecp2018/files/2149129/14.pptx)

https://github.com/40628414/vecp2018_14/blob/gh-pages/%E8%A8%88%E7%AE%97%E6%A9%9F%E7%A8%8B%E5%BC%8F%E5%A0%B1%E5%91%8A14.pptx

**Comment by a40628415** [comment]
[40628415.pptx](https://github.com/mdecourse/vecp2018/files/2149136/40628415.pptx)

**Comment by 40628454** [comment]
40628454.pptx

**Comment by 40328421** [comment]
[Lua40328421.pptx](https://github.com/mdecourse/vecp2018/files/2160500/Lua40328421.pptx)

**Comment by 40628454** [comment]
[Uploading 40628454.pptx…]()

**Comment by bobXDC** [comment]
![image](https://user-images.githubusercontent.com/36989467/42089457-c86f1e06-7bcf-11e8-9d48-b94f70149807.png)

**Comment by 40628454** [comment]
[ 40628454黃柏育.pptx…]()

**Comment by bobXDC** [comment]
40628401 LUA學習心得.pptx…]()

**Comment by bobXDC** [comment]
[Uploading LUA學習心得.pptx…]()

**Comment by 40628454** [comment]
[40628454黃柏育.pptx
](url)

**Comment by bobXDC** [comment]
[40628401 LUA學習心得.pptx](https://github.com/mdecourse/vecp2018/files/2149159/40628401.LUA.pptx)

**Comment by 40628428** [comment]
[LUA期末報告.pptx](https://github.com/mdecourse/vecp2018/files/2149160/LUA.pptx)

**Comment by 40628452** [comment]
[40628452溫凱傑.pptx](https://github.com/mdecourse/vecp2018/files/2149161/40628452.pptx)

**Comment by 40628454** [comment]
[40628454.pptx](https://github.com/mdecourse/vecp2018/files/2149163/40628454.pptx)

**Comment by 40628412** [comment]
[計算機程式報告.pptx](https://github.com/mdecourse/vecp2018/files/2149175/default.pptx)

**Comment by 40628411** [comment]
[計算機程式報告40628411.pptx](https://github.com/mdecourse/vecp2018/files/2149181/40628411.pptx)

**Comment by 40628418** [comment]
[計算機程式報告40628418.pptx](https://github.com/mdecourse/vecp2018/files/2149210/40628418.pptx)

**Comment by bobXDC** [comment]
[40628401 LUA學習心得.pptx](https://github.com/mdecourse/vecp2018/files/2149220/40628401.LUA.pptx)

**Comment by 40628413** [comment]
[40628413期末報告.pptx](https://github.com/mdecourse/vecp2018/files/2149288/40628413.pptx)

**Comment by 40628410** [comment]
[期末報告40628410.pptx](https://github.com/mdecourse/vecp2018/files/2149287/40628410.pptx)

**Comment by 40628405** [comment]
[計算機程式期末報告.pptx](https://github.com/mdecourse/vecp2018/files/2149291/default.pptx)

**Comment by 40628421** [comment]
計算機程式期末報告
[40628421.pptx](https://github.com/mdecourse/vecp2018/files/2149303/40628421.pptx)

**Comment by a40628450** [comment]
[40628450.pptx](https://github.com/mdecourse/vecp2018/files/2149307/40628450.pptx)

**Comment by 40628440** [comment]
[40628440.pptx](https://github.com/mdecourse/vecp2018/files/2149316/40628440.pptx)

**Comment by 40628416** [comment]
[40628416 期末簡報.pptx](https://github.com/mdecourse/vecp2018/files/2150151/40628416.pptx)
